# Generated by Django 5.2.6 on 2025-10-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("data_compra", models.DateField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("numero_nota_fiscal", models.CharField(blank=True, max_length=50)),
                (
                    "arquivo_nota_fiscal",
                    models.FileField(blank=True, null=True, upload_to="notas_fiscais/"),
                ),
                ("status", models.CharField(default="pendente", max_length=20)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "db_table": "compras",
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("contato", models.CharField(blank=True, max_length=100)),
                ("endereco", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "db_table": "fornecedores",
            },
        ),
        migrations.CreateModel(
            name="LogSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_id", models.IntegerField(null=True)),
                ("acao", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("tabela_afetada", models.CharField(blank=True, max_length=50)),
                ("registro_id", models.IntegerField(null=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "logs_sistema",
            },
        ),
        migrations.CreateModel(
            name="CompraItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto_id", models.IntegerField()),
                ("quantidade", models.IntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_item", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="app_admin.compra",
                    ),
                ),
            ],
            options={
                "db_table": "compra_itens",
            },
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrega", models.DateField()),
                ("responsavel_recebimento", models.CharField(max_length=100)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="app_admin.compra",
                    ),
                ),
            ],
            options={
                "db_table": "entregas",
            },
        ),
    ]
