# Generated by Django 5.2.6 on 2025-10-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_admin", "0001_initial"),
        ("app_solicitacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrega",
            name="solicitacao",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_solicitacoes.solicitacao",
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="fornecedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compras",
                to="app_admin.fornecedor",
            ),
        ),
    ]
