# Generated by Django 5.2.6 on 2025-09-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(max_length=100)),
            ],
        ),
    ]
