# Generated by Django 5.2.6 on 2025-09-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login",
            old_name="senha",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="login",
            old_name="email",
            new_name="username",
        ),
    ]
