# Generated by Django 5.2.6 on 2025-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("justificativa", models.TextField()),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                ("data_aprovacao", models.DateTimeField(blank=True, null=True)),
                ("data_negacao", models.DateTimeField(blank=True, null=True)),
                ("data_compra", models.DateTimeField(blank=True, null=True)),
                ("data_entrega", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovada", "Aprovada"),
                            ("negada", "Negada"),
                            ("consolidada", "Consolidada"),
                            ("comprada", "Comprada"),
                            ("entregue", "Entregue"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("observacoes_administrador", models.TextField(blank=True)),
                (
                    "total_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Solicitação",
                "verbose_name_plural": "Solicitações",
                "db_table": "solicitacoes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_item", models.DecimalField(decimal_places=2, max_digits=10)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Item de Solicitação",
                "verbose_name_plural": "Itens de Solicitação",
                "db_table": "solicitacao_itens",
            },
        ),
    ]
