# Generated by Django 5.2.6 on 2025-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Relatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("data_geracao", models.DateTimeField(auto_now_add=True)),
                ("conteudo", models.TextField()),
            ],
        ),
    ]
